use_frameworks!

platform :ios, '8.0'

target 'ApexDataCollect-Util_Example' do
  pod 'ApexDataCollect-Util', :path => '../'

  target 'ApexDataCollect-Util_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
